export const cpp = [
  {
    label: "#include <bits/stdc++.h>",
    detail: "常用头文件合集",
    type: "keyword",
    info: "一次性引入常见 STL 头文件，竞赛常用写法",
    boost: 95,
  },
  {
    label: "#include <iostream>",
    detail: "标准输入输出",
    type: "keyword",
    info: "引入 iostream，提供 std::cin / std::cout 等流式 IO",
    boost: 93,
  },
  {
    label: "using namespace std;",
    detail: "使用 std 命名空间",
    type: "keyword",
    info: "简化 std 前缀的引用，头文件引入后常见写法",
    boost: 91,
  },
  {
    label: "std::cout",
    detail: "标准输出流",
    type: "variable",
    info: "搭配 << 输出数据，可用 std::endl 或 '\\n' 换行",
    boost: 90,
    apply: "std::cout <<  << std::endl;",
  },
  {
    label: "std::cin",
    detail: "标准输入流",
    type: "variable",
    info: "搭配 >> 读取输入，常与 std::cout 配合提示",
    boost: 88,
    apply: "std::cin >> ;",
  },
  {
    label: "std::vector",
    detail: "动态数组",
    type: "class",
    info: "可变长顺序容器，支持 push_back / size / iter 访问",
    boost: 86,
    apply: "std::vector<int> v;",
  },
  {
    label: "std::string",
    detail: "字符串类",
    type: "class",
    info: "可变长字符串，支持拼接、substr、find 等操作",
    boost: 84,
    apply: "std::string s;",
  },
  {
    label: "std::sort",
    detail: "排序算法",
    type: "function",
    info: "std::sort(begin, end, cmp)：对区间排序，可自定义比较器",
    boost: 82,
    apply: "std::sort();",
  },
  {
    label: "std::pair",
    detail: "二元组",
    type: "class",
    info: "存储两个元素的容器，可通过 first/second 访问",
    boost: 80,
    apply: "std::pair<int, int> p;",
  },
  {
    label: "for(auto &x : container)",
    detail: "范围 for 循环",
    type: "keyword",
    info: "现代 C++ 遍历容器写法，可用 const auto& 避免拷贝",
    boost: 78,
    apply: "for (auto &x : ) {\n  \n}",
  },
  {
    label: "int main",
    detail: "程序入口",
    type: "keyword",
    info: "C++ 程序主函数模板，返回 0 表示正常退出",
    boost: 76,
    apply: "int main() {\n  \n  return 0;\n}",
  },
]
