export const turtle = [
  {
    label: "forward",
    detail: "向前移动",
    type: "function",
    info: "让海龟沿当前朝向向前移动指定距离",
    boost: 90,
    apply: "forward()",
  },
  {
    label: "backward",
    detail: "向后移动",
    type: "function",
    info: "让海龟沿当前朝向向后移动指定距离",
    boost: 88,
    apply: "backward()",
  },
  {
    label: "left",
    detail: "左转",
    type: "function",
    info: "让海龟左转指定角度（度数）",
    boost: 86,
    apply: "left()",
  },
  {
    label: "right",
    detail: "右转",
    type: "function",
    info: "让海龟右转指定角度（度数）",
    boost: 84,
    apply: "right()",
  },
  {
    label: "penup",
    detail: "抬笔",
    type: "function",
    info: "抬起画笔移动，不留下轨迹（也叫 up）",
    boost: 82,
    apply: "penup()",
  },
  {
    label: "pendown",
    detail: "落笔",
    type: "function",
    info: "放下画笔继续绘制轨迹（也叫 down）",
    boost: 80,
    apply: "pendown()",
  },
  {
    label: "goto",
    detail: "移动到坐标",
    type: "function",
    info: "移动到指定坐标，若画笔放下则绘制路径",
    boost: 78,
    apply: "goto()",
  },
  {
    label: "circle",
    detail: "画圆/弧",
    type: "function",
    info: "以当前位置为起点绘制圆或弧",
    boost: 76,
    apply: "circle()",
  },
  {
    label: "begin_fill",
    detail: "开始填充",
    type: "function",
    info: "开启填充模式，绘制封闭图形后与 end_fill 配合使用",
    boost: 74,
    apply: "begin_fill()",
  },
  {
    label: "end_fill",
    detail: "结束填充",
    type: "function",
    info: "结束填充模式，自动填充自 begin_fill 以来的闭合轨迹",
    boost: 72,
    apply: "end_fill()",
  },
  {
    label: "color",
    detail: "设置颜色",
    type: "function",
    info: "设置画笔与填充颜色，可单独或同时指定",
    boost: 70,
    apply: "color()",
  },
  {
    label: "speed",
    detail: "设置速度",
    type: "function",
    info: "设置绘制速度，1 最慢，10 最快",
    boost: 68,
    apply: "speed()",
  },
  {
    label: "setheading",
    detail: "设置朝向",
    type: "function",
    info: "将海龟朝向设置为绝对角度，0 度向东，90 度向北",
    boost: 66,
    apply: "setheading()",
  },
  {
    label: "home",
    detail: "回到原点",
    type: "function",
    info: "将海龟移动回原点并面向东，保持画笔状态",
    boost: 64,
    apply: "home()",
  },
  {
    label: "clear",
    detail: "清空画布",
    type: "function",
    info: "清除轨迹但不移动海龟位置与状态",
    boost: 62,
    apply: "clear()",
  },
  {
    label: "reset",
    detail: "重置画布",
    type: "function",
    info: "重置画布并将海龟回到初始位置与方向",
    boost: 60,
    apply: "reset()",
  },
  {
    label: "hideturtle",
    detail: "隐藏海龟",
    type: "function",
    info: "隐藏光标形状，仅绘制轨迹",
    boost: 58,
    apply: "hideturtle()",
  },
  {
    label: "showturtle",
    detail: "显示海龟",
    type: "function",
    info: "显示光标形状，恢复可见",
    boost: 56,
    apply: "showturtle()",
  },
  {
    label: "write",
    detail: "写文本",
    type: "function",
    info: "在当前位置写入文本，可指定对齐和字体",
    boost: 54,
    apply: "write()",
  },
  {
    label: "dot",
    detail: "画点",
    type: "function",
    info: "绘制一个指定直径与颜色的圆点",
    boost: 52,
    apply: "dot()",
  },
  {
    label: "pensize",
    detail: "设置笔粗",
    type: "function",
    info: "设置或获取画笔粗细",
    boost: 50,
    apply: "pensize()",
  },
  {
    label: "pencolor",
    detail: "设置笔色",
    type: "function",
    info: "设置或获取画笔颜色",
    boost: 48,
    apply: "pencolor()",
  },
  {
    label: "fillcolor",
    detail: "设置填充色",
    type: "function",
    info: "设置或获取填充颜色",
    boost: 46,
    apply: "fillcolor()",
  },
  {
    label: "bgcolor",
    detail: "设置背景色",
    type: "function",
    info: "设置画布背景颜色",
    boost: 44,
    apply: "bgcolor()",
  },
]
